# Generated by Django 4.0.10 on 2023-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('bnumber', models.CharField(db_column='Bnumber', max_length=100, primary_key=True, serialize=False)),
                ('baddress', models.CharField(blank=True, db_column='Baddress', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, db_column='PinCode', max_length=255, null=True)),
                ('mobileno1', models.BigIntegerField(db_column='MobileNo1')),
                ('mobileno2', models.BigIntegerField(blank=True, db_column='MobileNo2', null=True)),
                ('mobileno3', models.BigIntegerField(blank=True, db_column='MobileNo3', null=True)),
            ],
            options={
                'db_table': 'branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientrental',
            fields=[
                ('cnumber', models.CharField(db_column='Cnumber', max_length=100, primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, db_column='Cname', max_length=255, null=True)),
                ('caddress', models.CharField(blank=True, db_column='Caddress', max_length=255, null=True)),
                ('rdate', models.DateField(blank=True, db_column='Rdate', null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientRental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrent', models.FloatField(blank=True, db_column='Mrent', null=True)),
                ('paymentmethod', models.CharField(blank=True, db_column='PaymentMethod', max_length=255, null=True)),
                ('rdate', models.DateField(blank=True, db_column='Rdate', null=True)),
                ('fdate', models.DateField(blank=True, db_column='Fdate', null=True)),
                ('duration', models.FloatField(blank=True, db_column='Duration', null=True)),
                ('deposit', models.CharField(blank=True, db_column='Deposit', max_length=1, null=True)),
            ],
            options={
                'db_table': 'lease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ownermanage',
            fields=[
                ('ownno', models.CharField(db_column='OwnNo', max_length=255, primary_key=True, serialize=False)),
                ('ownname', models.CharField(blank=True, db_column='OwnName', max_length=255, null=True)),
                ('ownaddress', models.CharField(blank=True, db_column='OwnAddress', max_length=255, null=True)),
                ('ownbusinesstype', models.CharField(blank=True, db_column='OwnBusinessType', max_length=255, null=True)),
                ('ownmno', models.BigIntegerField(blank=True, db_column='OwnMno', null=True)),
            ],
            options={
                'db_table': 'ownerManage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pnumber', models.CharField(db_column='Pnumber', max_length=100, primary_key=True, serialize=False)),
                ('ptype', models.CharField(blank=True, db_column='PType', max_length=100, null=True)),
                ('rooms', models.IntegerField(blank=True, db_column='Rooms', null=True)),
                ('rent', models.FloatField(blank=True, db_column='Rent', null=True)),
                ('paddress', models.CharField(blank=True, db_column='Paddress', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, db_column='Pin', max_length=255, null=True)),
                ('isavailable', models.IntegerField(db_column='isAvailable')),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffno', models.CharField(db_column='staffNo', max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('bdate', models.DateField(blank=True, db_column='Bdate', null=True)),
                ('mno1', models.BigIntegerField(db_column='Mno1')),
                ('mno2', models.BigIntegerField(blank=True, db_column='Mno2', null=True)),
                ('mno3', models.BigIntegerField(blank=True, db_column='Mno3', null=True)),
                ('salary', models.IntegerField(blank=True, db_column='Salary', null=True)),
                ('sposition', models.CharField(blank=True, db_column='SPosition', max_length=255, null=True)),
                ('super_id', models.CharField(blank=True, db_column='Super_id', max_length=255, null=True)),
                ('bonus', models.IntegerField(blank=True, db_column='Bonus', null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_date', null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
