# Generated by Django 4.0.10 on 2023-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.IntegerField(db_column='InvoiceId', primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Invoice',
                'managed': False,
            },
        ),
    ]
